# Generated by Django 5.1.3 on 2024-11-15 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NexusMusic', '0004_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='uploaded_by',
            new_name='user',
        ),
    ]
