# Generated by Django 5.1.3 on 2024-11-15 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NexusMusic', '0005_rename_uploaded_by_song_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='user',
            new_name='uploaded_by',
        ),
    ]
