# Generated by Django 5.1.3 on 2024-11-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NexusMusic', '0006_rename_user_song_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
